## 03 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 

In [2]:
iris = datasets.load_iris()
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

分离出一部分数据做训练，另外一部分数据做测试。

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
#取出x所有的索引的随机数排列
shuffled_indexes = np.random.permutation(len(X))
shuffled_indexes

array([ 64,  62,   8,  74,  85,  47, 101,  66, 114,  57,  25, 110,  77,
       136, 128,  32, 144,  42, 135,  11, 123, 149,   4, 118,  91,  92,
        23, 111,  40,  53,  86,  54,  94,  34, 103,  78, 119,  84,  29,
        82, 116,  26,   3,  12, 126, 121,  69,  83,  36,  73, 100,  14,
       117,  48,  80,  90, 124,  51, 113,  22,  70, 129, 106,   9, 107,
        33,  18,  35, 105,  52,  61, 130, 115,  41,  95,  31,  13,  58,
         2, 145, 148,  87,   6,  20,  15,  79,  59,  37,  27,  39, 133,
        99,  16,  56, 147,  49,  96,  55,  45, 131,  60, 139, 132, 112,
        43, 146, 102,  65,  67,  38, 125,  75,  28,  81, 140,  17,  21,
        30,  10, 141,  76,  19, 137, 138,  93, 134, 122,  71,  24, 120,
        44,   7,   5,  88,  46,   0,  98,  89,  72, 104,   1, 143,  50,
        63, 127, 142,  68,  97, 108, 109])

In [9]:
# 2 8分 20%当测试数据集
test_ratio = 0.2 
#获取测试数据的大小
test_size = int(len(X) * test_ratio)

In [27]:
#测试数据集索引
test_indexes = shuffled_indexes[:test_size]
#训练数据集索引
train_indexes = shuffled_indexes[test_size:]


In [28]:
#训练数据值
X_train = X[train_indexes]
#训练标签值
y_train = y[train_indexes]
# 测试数据集
X_test = X[test_indexes]
#测试数据集
y_test = y[test_indexes]

In [12]:
#训练数组
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
#测试
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 封装

In [14]:
#从我们封装的获取方法 train_test_split
from playML.model_selection import train_test_split
#返回 测试 和 训练 数据集
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
#训练样本120个
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [16]:
#测试样本30个
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


#### 测试我们的算法

In [17]:
#我们自己的包中导入
from playML.kNN import KNNClassifier
#设置临近的几个点 ,参3就是3个点
my_knn_clf = KNNClassifier(k=3)
#让分类器进行拟合的过程,就是训练
my_knn_clf.fit(X_train, y_train)
# 将测试数据传入测试 y_predict 包含30个数据 
y_predict = my_knn_clf.predict(X_test)

In [18]:
#包含30个数据
y_predict

array([1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 0, 2, 1, 2, 0, 0, 2, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0])

In [19]:
#测试结果数据
y_test

array([1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0, 2, 2,
       2, 2, 1, 1, 1, 2, 0, 0])

In [20]:
#数一下有好多值相等 ,也就是等于 true
sum(y_predict == y_test)

29

In [21]:
#求出预测准确率 ,其实就是 预测的个数 / 预测总量(训练数)
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

#### sklearn中的train_test_split

In [22]:
from sklearn.model_selection import train_test_split

train_test_split

<function sklearn.model_selection._split.train_test_split(*arrays, **options)>

In [23]:
# 分割数据集 ,分割比例是 test_size = 0.2, random_state 是随机种子,好让每次产生的都一样                                   
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
